# Generated by Django 3.1.2 on 2020-10-21 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201021_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
