# Generated by Django 3.1.2 on 2020-10-21 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201021_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата рождения'),
        ),
    ]
