# Generated by Django 3.1.1 on 2020-10-20 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learn_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(help_text='Введите цифру и букву', max_length=20, unique=True, verbose_name='Класс')),
                ('url', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Введите фамилию', max_length=200, verbose_name='Фамилия')),
                ('name', models.CharField(help_text='Введите имя', max_length=200, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, help_text='Введите отчество(при наличии)', max_length=200, verbose_name='Отчество')),
                ('mail', models.CharField(max_length=300, unique=True, verbose_name='Почта')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='readers.learn_class')),
            ],
        ),
    ]
